"""Fetching module for downloading scientific articles and datasets."""

from odda_utils.fetching.geo import (
    GEODownloadResult,
    GEOFileInfo,
    GEOFileSizeResult,
    GSEMetadata,
    download_gse_dataset,
    fetch_gse_metadata,
    get_gse_file_sizes,
)
from odda_utils.fetching.iprox import (
    IPXDownloadResult,
    IPXMetadata,
    download_ipx_dataset,
    fetch_ipx_metadata,
)
from odda_utils.fetching.massive import (
    MSVDownloadResult,
    MSVFileInfo,
    MSVFileSizeResult,
    MSVMetadata,
    download_msv_dataset,
    fetch_msv_metadata,
    get_msv_file_sizes,
)
from odda_utils.fetching.pmc import (
    ArchiveContentsResult,
    ArchiveFileInfo,
    ArticleMetadata,
    download_pmc_article,
    fetch_article_metadata,
    list_archive_contents,
    search_pubmed,
)
from odda_utils.fetching.pxd import (
    CatalogResult,
    PXDDownloadResult,
    PXDFileInfo,
    PXDFileMetadata,
    PXDFilesMetadataResult,
    PXDFileSizeResult,
    PXDMetadata,
    PXDPublicationRef,
    URLDownloadResult,
    catalog_local_dataset_files,
    catalog_local_dataset_files_with_llm,
    download_files_from_urls,
    download_pxd_dataset,
    fetch_pxd_files_metadata,
    fetch_pxd_metadata,
    get_pxd_file_sizes,
)
from odda_utils.metadata import FullArticleMetadata

__all__ = [
    "ArchiveContentsResult",
    "ArchiveFileInfo",
    "ArticleMetadata",
    "CatalogResult",
    "FullArticleMetadata",
    "GEODownloadResult",
    "GEOFileInfo",
    "GEOFileSizeResult",
    "GSEMetadata",
    "IPXDownloadResult",
    "IPXMetadata",
    "MSVDownloadResult",
    "MSVFileInfo",
    "MSVFileSizeResult",
    "MSVMetadata",
    "PXDDownloadResult",
    "PXDFileInfo",
    "PXDFileMetadata",
    "PXDFilesMetadataResult",
    "PXDFileSizeResult",
    "PXDMetadata",
    "PXDPublicationRef",
    "URLDownloadResult",
    "catalog_local_dataset_files",
    "catalog_local_dataset_files_with_llm",
    "download_files_from_urls",
    "download_gse_dataset",
    "download_ipx_dataset",
    "download_msv_dataset",
    "download_pmc_article",
    "download_pxd_dataset",
    "fetch_article_metadata",
    "fetch_gse_metadata",
    "fetch_ipx_metadata",
    "fetch_msv_metadata",
    "fetch_pxd_files_metadata",
    "fetch_pxd_metadata",
    "get_gse_file_sizes",
    "get_msv_file_sizes",
    "get_pxd_file_sizes",
    "list_archive_contents",
    "search_pubmed",
]
